---

- name: Copy pam-auth-update wrapper script
  copy:
    src: usr/local/sbin/wpengine-pam-auth-update.sh
    dest: /usr/local/sbin/wpengine-pam-auth-update.sh
    owner: root
    group: root
    mode: 0750
  notify:
    - pam-auth-update

- name: Ensure pam-configs
  copy:
    src: usr/share/pam-configs/{{ item }}
    dest: /usr/share/pam-configs/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - mkhomedir
  notify:
    - pam-auth-update

- name: ensure Apparmor allows sssd to notify systemd via local/usr.sbin.sssd
  copy:
    src: etc/apparmor.d/local/usr.sbin.sssd
    dest: /etc/apparmor.d/local/usr.sbin.sssd
    owner: root
    group: root
    mode: 0644
  notify: apparmor reload
  when: ansible_lsb.major_release|int == 16

- name: Install sssd packages
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  with_items:
    - sssd
    - apparmor-utils
  register: sssd_installed
  notify:
    - restart sssd

- name: check for apparmor kernel support
  stat: path=/sys/kernel/security/apparmor
  failed_when: false
  changed_when: false
  register: apparmor_present

- name: Check sssd apparmor profile
  shell: "pgrep sssd | xargs -r -I% cat /proc/%/attr/current | grep '(enforce)$'"
  when: apparmor_present is defined and apparmor_present.stat is defined and apparmor_present.stat.exists
  register: sssd_apparmor
  changed_when: "sssd_apparmor.rc != 0"
  failed_when: false
  notify: aa-enforce sssd

- name: Ensure /etc/sssd/sssd.conf
  template:
    src: etc/sssd/sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  tags:
    - creds
    - sssd
  notify: restart sssd

#- name: Enable sssd service
#  service:
#    name: sssd
#    enabled: yes
#    state: started

- name: Configure NSS to use sss
  lineinfile:
    dest: /etc/nsswitch.conf
    line: '{{ item }}:       files sss'
    regexp: '^{{ item }}:'
    state: present
  with_items:
    - passwd
    - group
    - sudoers

- import_tasks: user-mapping.yml
  when: is_farm
  tags:
    - ldap_user_mapping
