---

- name: Ensure /usr/local/sbin
  file:
     path: /usr/local/sbin
     state: directory
     owner: root
     group: root
     mode: 0775

- name: Copy ldap user mapping script
  copy:
    src: usr/local/sbin/ldap-user-mapping.sh
    dest: /usr/local/sbin/ldap-user-mapping.sh
    owner: root
    group: root
    mode: 0750

- name: Configure ldap user mapping cron
  cron:
    name: "LDAP User Mapping"
    minute: "{{ my.cluster.id | default(0) % 59 }}"
    user: root
    job: "bash /usr/local/sbin/ldap-user-mapping.sh 2>&1 | logger -t LDAP_USER_MAPPING"
    cron_file: ldap-user-mapping
