---
- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Restart fail2ban
  command: echo TODO figure out why this no work well
  # service:
  #  name: fail2ban
  #  state: restarted
