---
# tasks file for security

- include: chkrootkit.yml
  tags: chkrootkit

- include: fail2ban.yml
  tags: fail2ban

- include: rkhunter.yml
  tags: rkhunter

- name: Ensure clamscan runner script at /usr/local/sbin/clamscan_sys_dirs
  copy:
    src: usr/local/sbin/clamscan_sys_dirs.sh
    dest: /usr/local/sbin/clamscan_sys_dirs
    owner: root
    group: root
    mode: 0700
  tags: clamscan

- name: Run clamscan script /usr/local/sbin/clamscan_sys_dirs daily via crontab
  cron:
    name: "Scans contents of /etc/ and select system directories daily"
    minute: "13"
    hour: "13"
    job: "/usr/local/sbin/clamscan_sys_dirs 2>&1 | logger -t CLAMSCAN_USR"
    cron_file: clamscan_sys_dirs
    user: root
  tags: clamscan
