---

- name: Ensure pip is intalled
  apt:
    pkg: python-pip
    state: present
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time | default(600) }}"

- name: Ensure Supervisor is installed (specific version).
  pip:
    name: supervisor
    state: present
    version: "{{ supervisor_version }}"
  when: supervisor_version != 'latest'

- name: Ensure Supervisor is installed (latest version).
  pip:
    name: supervisor
    state: present
  when: supervisor_version == 'latest'

- name: Ensure Supervisor log dir exists.
  file:
    path: "{{ supervisor_log_dir }}"
    state: directory
    mode: 0755

- name: Import configuration tasks
  include: config.yml

- name: Import tasks to set up supervisor service
  include: init-setup.yml
  when: supervisor_started or supervisor_enabled

- name: Ensure Supervisor is started (if configured).
  service:
    name: supervisord
    state: started
  when: supervisor_started
  tags:
    - bootstrap
    - always

- name: Ensure Supervisor is enabled at boot (if configured).
  service:
    name: supervisord
    enabled: yes
  when: supervisor_enabled
  tags:
    - bootstrap
    - always
