---

- name: Vault Restart Handler
  supervisorctl:
    name: vault
    state: restarted
  listen: 'Vault Restart'
  tags:
    - bootstrap

- name: Update CA certificates
  command: update-ca-certificates
