---

- name: OS packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ consul_os_packages }}"
  tags: installation

- name: Check Consul package file
  local_action: stat path="{{ role_path }}/files/{{ consul_pkg }}"
  become: no
  run_once: true
  register: consul_package

- name: Download Consul
  local_action: get_url url="{{ consul_zip_url }}" dest="{{ role_path }}/files/{{ consul_pkg }}" checksum="sha256:{{ consul_sha256 }}" timeout="42"
  become: no
  run_once: true
  tags: installation
  when: not consul_package.stat.exists | bool

- name: Unarchive Consul
  local_action: unarchive src="{{ role_path }}/files/{{ consul_pkg }}" dest="{{ role_path }}/files/" creates="{{ role_path }}/files/consul"
  become: no
  run_once: true
  changed_when: false
  tags: installation

- name: Install Consul
  copy:
    src: "{{ role_path }}/files/consul"
    dest: "{{ consul_bin_path }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0755"
  tags: installation

- name: Cleanup
  local_action: file path="{{ item }}" state="absent"
  become: no
  with_fileglob: "{{ role_path }}/files/consul"
  run_once: true
  changed_when: false
  tags: installation
