---

- name: clean deb system users
  when: ansible_os_family == "Debian"
  user: name={{ item }} state=absent
  with_items:
    - gnats
    - irc

- name: clean ubuntu system users
  when: ansible_distribution == "Ubuntu"
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
    force: yes
  failed_when: false
  with_items:
    - ubuntu
  tags:
    - bootstrap_web
    - bootstrap_storage
    - bootstrap_utility

- name: clean general system users
  user: name={{ item }} state=absent
  with_items:
    - games
