---

- name: Ensure /etc subdirectories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - '/etc/profile.d'
    - '/etc/bash_completion.d'

- name: Manage /etc/securetty
  copy:
    src: etc/securetty
    dest: /etc/securetty
    owner: root
    group: root
    mode: 0644
  tags:
    - securetty

- name: Template SSH configs
  template:
    src: etc/ssh/{{ item }}
    dest: /etc/ssh/{{ item }}
  with_items:
    - ssh_config
    - sshd_config
  tags:
    - ssh
  notify:
    - ssh restart

- name: Configure screenrc
  lineinfile:
    dest: /etc/screenrc
    line: '{{ item.key }} {{ item.value }}'
    regexp: '{{ item.key }}'
  with_dict:
    startup_message: 'off'
    shell: '-$SHELL'

- name: /etc/profile
  copy:
    src: etc/profile
    dest: /etc/profile
    owner: root
    group: root
    mode: 0644

- name: Copy profile.d scripts
  template:
    src: 'etc/profile.d/{{ item }}'
    dest: /etc/profile.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - wpengine.sh

- name: Copy bash_completion.d scripts
  copy:
    src: 'etc/bash_completion.d/{{ item }}'
    dest: /etc/bash_completion.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - wpengine

- name: ensure /etc/rc.local...
  template: src=etc/rc.local dest=/etc/rc.local owner=root group=root mode=0755
  when: "ansible_os_family == 'Debian'"
  notify: rc.local reload
