---
- include: ../../testinfra.yml

# load non-group var overrides

- name: Load operating system specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  check_mode: no
  tags: always

- include: root.yml
  tags:
    - root_profile

- include: system.yml
- include: packages.yml
- include: iptables.yml
  tags:
    - iptables
    - modify_cluster
- include: postfix.yml
  tags: postfix
- include: etcwpengine.yml
- include: cron.yml
- include: etc.yml
- include: rsyslog.yml
  tags: rsyslog
#- include: php.yml
#  tags: php

- include: logrotate.yml
  tags: logrotate

- include: sysstat.yml
  when: ansible_os_family == "Debian"
  tags: sysstat

- name: ensure /etc/gitconfig ...
  template: src=etc/gitconfig dest=/etc/gitconfig owner=root group=root mode=0644
  tags:
    - bootstrap_web
    - bootstrap_utility

- name: ensure /var/log/wpe/
  file: dest=/var/log/wpe state=directory

- include: clean_users.yml
  when: ansible_os_family == "Debian"

- include: new_etc_hosts.yml
  when: use_manual_hosts is not defined
  tags:
    - hostsfile

- include: tmpreaper.yml

- name: Template /etc/hosts when use_manual_hosts
  template:
    src: etc/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: use_manual_hosts is defined and (packer_builder_type is not defined or packer_builder_type != "docker")
  tags:
    - hostsfile

# See https://wpengine.atlassian.net/browse/QE-3090
- name: Ensure inventory hostname is always in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: '127.0.0.1 {{ ansible_hostname }}'
  when: is_development is defined and is_development and (packer_builder_type is not defined or packer_builder_type != "docker")
  tags:
   - hostsfile

- name: Record the cluster id
  template:
    src=etc/cluster-id
    dest=/etc/cluster-id
    owner=root
    group=root
    mode=0644

- name: Record host info
  template:
    src={{ item }}
    dest=/{{ item }}
    owner=root
    group=root
    mode=0644
  when: "'corporate' not in group_names"
  with_items:
    - "etc/cluster-type"
    - "etc/cluster-datacenter"

- include: td-agent.yml
  when: fluentd_enabled
  # See also: roles/gophpr/tasks/main.yml include of td-agent.yml, please keep in sync
  tags:
    - td-agent
