---

- name: Ensure /etc/hosts header for dev and staging
  template:
    src=etc/wpengine/host_header
    dest=/etc/wpengine/host_header
    owner=root
    group=root
    mode=0644
  when: is_development is defined and is_development and use_manual_hosts is not defined
  tags:
    - hostsfile
    - bootstrap_web
    - bootstrap_storage
    - bootstrap_utility

- name: Enable dynamic hosts
  lineinfile:
    line=''
    create=yes
    state=present
    dest=/etc/wpengine/enabled/dynamic_etc_hosts

- name: Ensure server_meta python script in /etc/wpengine/bin/
  copy:
    src=../../../inventory/{{ item }}
    dest=/etc/wpengine/bin/{{ item }}
  with_items:
  - server_meta.py
  - wpe_cnf.py


- name: Ensure /etc/hosts wrapper exists
  copy:
    src=etc/wpengine/bin/etc_hosts.py
    dest=/etc/wpengine/bin/
    owner=root
    group=root
    mode=0755
  notify: etc_hosts first run

- name: Ensure /etc/hosts cron job
  cron:
    name="/etc/hosts cron"
    minute={{ my.cluster.id % 60 }}
    user="root"
    job="python /etc/wpengine/bin/etc_hosts.py 2>&1 | /usr/bin/logger -t ETCHOSTS"
    cron_file=etc_hosts
    state=present
  tags:
    - bootstrap_web
    - bootstrap_storage
    - bootstrap_utility
