---

- name: remove unused PHP packages
  apt:
    pkg: "{{ item }}"
    state: absent
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  with_items:
    - "{{ remove_php_packages }}"
  when: ansible_os_family == "Debian"
  tags:
    - packages

- name: install PHP packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  with_items:
    - "{{ php_packages }}"
  when: ansible_os_family == "Debian"
  tags:
    - packages

- name: Set php-cli alternatives
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  with_items:
    - "{{ php_cli_alternatives }}"
  tags:
    - alternatives

- name: Template php.ini for CLI SAPI
  template:
    src: etc/php/cli/php.ini
    dest: "{{ php_cli_conf_path }}/php.ini"
    owner: root
    group: root
    mode: "0644"

- name: debug
  debug: var=is_farm

- name: Template php.ini for wp-cli CLI SAPI
  template:
    src: etc/php/cli/php.ini
    dest: "{{ php_wpcli_conf_path }}/php.ini"
  when: ( php_wpcli_conf_path is defined ) and ( "{{ php_wpcli_conf_path }}" != "{{ php_cli_conf_path }}" )

- name: Fix deprecated comment styles in PHP confs
  lineinfile: dest={{ item }} regexp='^#(.*)' line=';\1' backrefs=yes
  when: ansible_os_family == "Debian" and php_cli_avail_path is defined
  with_fileglob:
    - "{{ php_cli_avail_path | default([]) }}/*.ini"

- name: Install CLI PECL packages
  command: "pecl install pecl.php.net/{{ item.module | default(item) }}{% if item.version is defined %}-{% endif %}{{ item.version | default() }}"
  register: pecl_install_output
  changed_when: "'install ok' in  pecl_install_output.stdout"
  failed_when: "'ERROR' in pecl_install_output.stdout and 'already installed and is the same' not in pecl_install_output.stdout"
  with_items:
    - "{{ php_cli_pecl_modules }}"
  tags:
    - php-pecl

- name: Set up CLI PECL module INI files
  lineinfile:
    dest: "{{ php_cli_avail_path | default( php_cli_conf_module_path ) }}/{{ item.module | default(item) }}.ini"
    line: "extension={{ item.module | default(item) }}.so"
    create: yes
    insertafter: BOF
  with_items:
    - "{{ php_cli_pecl_modules }}"
  tags:
    - php-pecl

- name: Enable CLI SAPI PHP modules
  command: "bash /etc/wpengine/bin/enmod-wrapper.sh {{ item }} cli ALL"
  register: enmod
  changed_when: '"Enabled {{ item }}" in enmod.stdout'
  with_items:
    - imap
    - mcrypt
    - "{{ php_cli_pecl_modules }}"

- name: Disable CLI SAPI PHP modules
  command: "bash /etc/wpengine/bin/dismod-wrapper.sh {{ item }} cli ALL"
  register: dismod
  changed_when: '"Disabled {{ item }}" in dismod.stdout'
  with_items:
    - xdebug
