---

- name: ensure postfix required packages installed...
  apt:
    pkg: "{{ item }}"
    state: present
  when: ansible_os_family == "Debian"
  with_items:
    - postfix
    - postfix-pcre
    - moreutils
    - proxsmtp
  tags:
    - packages

- name: ensure postfix runlevel
  service: name=postfix enabled=yes

#- name: ensure postfix required packages installed...
#  yum: pkg={{ item }} state=present
#  with_items:
#    - postfix
#  tags:
#    - packages

- name: ensure /etc/postfix directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/postfix
    - /etc/postfix/ssl
  tags:
    - bootstrap_web
    - bootstrap_utility

- name: ensure /etc/postfix/*
  template: src=etc/postfix/{{ item }} dest=/etc/postfix/{{ item }} owner=root group=root mode=0644
  with_items:
    - main.cf
    - master.cf
    - relay.pcre
    - headers.pcre
    - sender.pcre
    - recipient.pcre
    - ssl/gd_bundle.crt
    - ssl/GeoTrust_Global_CA.pem
  notify:
    - postfix restart
  retries: 5
  tags:
    - bootstrap_web
    - bootstrap_utility

- name: ensure proxsmtp group
  group: name=proxsmtp state=present

- name: ensure proxsmtp user
  user: name=proxsmtp state=present shell=/usr/sbin/nologin system=yes home=/var/spool/proxsmtp group=proxsmtp

- name: ensure /var/spool/proxsmtp
  file: path=/var/spool/proxsmtp state=directory owner=proxsmtp group=proxsmtp mode=0775

- name: ensure proxsmtp service enabled
  service: name=proxsmtp enabled=yes

- name: ensure modified proxsmtp init script
  copy: src=etc/init.d/proxsmtp dest=/etc/init.d/proxsmtp owner=root group=root mode=0755
  notify:
    - systemctl daemon-reload
    - proxsmtp restart

- name: ensure /etc/proxsmtp/proxsmtpd.conf
  copy: src=etc/proxsmtp/proxsmtpd.conf dest=/etc/proxsmtp/proxsmtp.conf owner=root group=proxsmtp mode=0644
  notify:
    - proxsmtp restart

- name: copy proxsmtp config files
  copy:
    src: etc/proxsmtp/{{ item.file }}
    dest: /etc/proxsmtp/{{ item.file }}
    owner: root
    group: proxsmtp
    mode: "{{ item.mode | default(0644) }}"
  with_items:
    - { file: wpengine_queue_filter.sh, mode: "0755" }
    - { file: evil_headers.txt }

- name: ensure /etc/cron.daily/proxsmtpd_restart
  copy: src=etc/cron.daily/proxsmtpd_restart dest=/etc/cron.daily/proxsmtpd_restart owner=root group=root mode=0755

- name: ensure /etc/postfix/virtual* when is_development
  template: src=etc/postfix/{{ item }} dest=/etc/postfix/{{ item }} owner=root group=root mode=0644
  when: is_development is defined and is_development
  with_items:
    - virtual_aliases.pcre
    - virtual_domains.pcre
  notify:
    - postfix restart

- name: ensure /usr/local/sbin/postfix_count_deferred.sh
  copy:
    src: usr/local/sbin/postfix_count_deferred.sh
    dest: /usr/local/sbin/postfix_count_deferred.sh
    owner: root
    group: root
    mode: 0754

- name: configure postfix deferred queue monitoring cron
  cron:
    name: Count postfix deferred queue
    user: root
    job: bash /usr/local/sbin/postfix_count_deferred.sh
    cron_file: postfix_count_deferred
    minute: "*/5"
