---

- name: Template /etc/apparmor.d/usr.sbin.rsyslogd
  template:
    src: etc/apparmor.d/usr.sbin.rsyslogd
    dest: /etc/apparmor.d/usr.sbin.rsyslogd
  when: ansible_distribution == "Ubuntu"
  notify:
    - apparmor reload

- name: Enable /etc/rsyslog.conf socket
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$InputUnixListenSocketCreatePath'
    line: '$InputUnixListenSocketCreatePath on'
  notify:
    - rsyslog restart

- name: Enable /etc/rsyslog.conf open the socket
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$AddUnixListenSocket'
    line: '$AddUnixListenSocket /var/run/syslog-socket'
    owner: root
    group: root
    mode: 0644
    state: present
  notify: rsyslog restart

- name: Template rsyslog.d config files
  template:
    src: etc/rsyslog.d/{{ item }}.conf
    dest: /etc/rsyslog.d/{{ item }}.conf
    owner: root
    group: root
    mode: 0644
  with_items:
    - 50-default
    - 29-cmdline

- name: Create rsyslog log targets
  file:
    path: /var/log/{{ item.key }}
    state: touch
    owner: syslog
    group: "{{ item.value }}"
    mode: 0640
  changed_when: false
  with_dict:
    auth.log: adm
    cmdline.log: adm
    cron.log: adm
    daemon.log: adm
    debug: syslog
    kern.log: adm
    lpr.log: adm
    mail.err: syslog
    mail.info: syslog
    mail.log: adm
    mail.warn: adm
    messages: syslog
    syslog: adm
    user.log: adm
  notify:
    - rsyslog restart
