---

- name: Configure sysstat
  copy:
    src: etc/default/sysstat
    dest: /etc/default/sysstat
  notify: sysstat restart

- name: Ensure /var/log/sysstat
  file:
    path: /var/log/sysstat
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Configure sysstat five-minute cron job
  cron:
    name: "Activity reports every 5 minutes everyday"
    minute: "*/5"
    job: "/usr/lib/sysstat/debian-sa1 -L 1 1 2>&1 | logger -t SYSSTAT"
    cron_file: sysstat_wpengine
    user: root

- name: Configure sysstat daily cron job
  cron:
    name: "Additional run at 23:59 to rotate the statistics file"
    hour: 23
    minute: 58
    job: "/usr/lib/sysstat/debian-sa1 -L 60 2 2>&1 | logger -t SYSSTAT"
    cron_file: sysstat_wpengine
    user: root

- name: Clobber default sysstat cron jobs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/cron.d/sysstat
