---

- name: ensure /tmp...
  file: dest=/tmp owner=root group=root mode=01777 state=directory

- name: Ensure /etc/localtime symlink
  file: src=/usr/share/zoneinfo/{{ localtime }} dest=/etc/localtime owner=root group=root state=link force=yes

#- name: ensure /etc/timezone...
#  template:
#    src: etc/timezone
#    dest: /etc/timezone
#    owner: root
#    group: root
#    mode: 0644

#- name: ensure /etc/resolv.conf
#  template:
#    src: etc/resolv.conf
#    dest: /etc/resolv.conf
#    owner: root
#    group: root
#    mode: 0644
#  when: not use_vendor_dns

- name: ensure /etc/sudoers...
  include: sudoers.yml
  tags: sudoers

- name: set hostname
  hostname:
    name: "{{ my.server.name }}"
  tags:
    - bootstrap_web
    - bootstrap_storage
    - bootstrap_utility
  when: packer_builder_type is defined and packer_builder_type != "docker"

- name: ensure sudo group...
  group: name=sudo state=present system=yes

- name: /etc/sysctl.conf
  template: src=etc/sysctl.conf dest=/etc/sysctl.conf owner=root group=root mode=0644
  notify: sysctl reload

- name: /etc/modprobe.d
  file:
    path: /etc/modprobe.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: /etc/modprobe.d/ contents
  copy:
    src: etc/modprobe.d/{{ item }}.conf
    dest: /etc/modprobe.d/{{ item }}.conf
    owner: root
    group: root
    mode: 0644
  with_items:
    - nf_conntrack

- name: /etc/security/limits.conf
  template: src=etc/security/limits.conf dest=/etc/security/limits.conf owner=root group=root mode=0644

- name: Set up our apt.conf.d
  copy: src=etc/apt/apt.conf.d/{{ item }} dest=/etc/apt/apt.conf.d/ owner=root group=root mode=0644
  when: ansible_os_family == "Debian"
  with_items:
    - 10periodic
    - 50unattended-upgrades

- name: Suppress output from update-notifier-common where it exits
  lineinfile:
    dest: /etc/cron.weekly/update-notifier-common
    state: present
    create: no
    backrefs: yes
    regexp: '^/usr/lib/ubuntu-release-upgrader/release-upgrade-motd$'
    line: '/usr/lib/ubuntu-release-upgrader/release-upgrade-motd >/dev/null 2>&1'
  failed_when: false
