---

- name: Set apt preferences for td-agent
  template:
    src: etc/apt/preferences.d/td-agent.pref
    dest: /etc/apt/preferences.d/td-agent.pref
    owner: root
    group: root
    mode: 0644

# While we're potentially switching td-agent/fluentd versions, we need to ensure we have the correct gem versions, and
# consequently the td-agent group & user, before we install the td-agent package
- name: Ensure td-agent group
  group:
    name: td-agent
    system: yes

- name: Ensure td-agent user
  user:
    name: td-agent
    group: td-agent
    system: yes
    createhome: no
    shell: /usr/sbin/nologin
    state: present

# We're currently maintaining two gem-path directories to accommodate multiple versions of td-agent/fluentd
- name: Ensure directory under /opt/td-agent to store bundler-managed gems
  file:
    path: "{{ td_agent_gem_path }}"
    state: directory
    owner: td-agent
    group: td-agent
    mode: 0750

- name: Ensure /etc/td-agent directory
  file:
    path: /etc/td-agent
    state: directory
    owner: td-agent
    group: td-agent
    mode: 0750

- name: Template Gemfile & Gemfile.lock for the appropriate td-agent version to /etc/td-agent
  template:
    src: etc/td-agent/Gemfile-{{ td_agent_pin_version }}{{ item }}
    dest: /etc/td-agent/Gemfile{{ item }}
    owner: td-agent
    group: td-agent
    mode: 0640
  with_items:
    - ""
    - ".lock"
  notify:
    - td-agent restart

- name: Template /etc/default/td-agent in order to add extra flags to the td-agent service command
  template:
    src: etc/default/td-agent
    dest: /etc/default/td-agent
    owner: td-agent
    group: td-agent
    mode: 0640
  register: td_agent_gemfile
  notify:
    - td-agent restart

- name: Ensure pinned version of td-agent is present
  apt:
    name: td-agent={{ td_agent_pin_version }}.*
    force: yes
    state: present
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  register: apt_task
  until: apt_task.failed is not defined
  retries: 3
  delay: 30

- name: Ensure bundler-managed gems for td-agent are installed
  bundler:
    executable: /opt/td-agent/embedded/bin/bundle
    gem_path: "{{ td_agent_gem_path }}"
    gemfile: "{{ td_agent_gemfile_path }}"
    state: present
  become: true  # the gems installed by this instance of bundler need to be readable by the td-agent service's user
  become_user: td-agent

- name: Remove gems incompatabile with td-agent 2.x
  gem:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    executable: /usr/sbin/td-agent-gem
    user_install: false
    state: absent
  with_dict:
    googleauth: "0.5.2"
    fluent-plugin-bigquery: "1.0.0"
    fluentd: "~> 0.14.0"
  when: td_agent_pin_version == '2'
  notify:
    - td-agent restart

- name: Ensure fluentd gems > 0.14.19 for td-agent 3.x installations
  gem:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    executable: /usr/sbin/td-agent-gem
    user_install: false
    state: present
  with_dict:
    fluentd: "~> 0.14.19"
  when: td_agent_pin_version == '3'
  notify:
    - td-agent restart

- name: td-agent ca certificate
  copy:
    src: etc/td-agent/ca.pem
    dest: /etc/td-agent/ca.pem
    owner: td-agent
    group: td-agent
    mode: 0644
  notify:
    - td-agent restart

- name: td-agent gcp key
  template:
    src: etc/td-agent/key.json
    dest: /etc/td-agent/key.json
    owner: td-agent
    group: td-agent
    mode: 0640
  notify:
    - td-agent restart

- name: td-agent config
  template:
    src: etc/td-agent/td-agent-{{ td_agent_pin_version }}.conf
    dest: /etc/td-agent/td-agent.conf
    owner: td-agent
    group: td-agent
    mode: 0640
  notify:
    - td-agent restart

- name: ensure td-agent config folder
  file:
    path: /etc/td-agent/config.d
    state: directory
    owner: td-agent
    group: td-agent
    mode: 0750
  notify:
    - td-agent restart

- name: td-agent syslog config
  template:
    src: etc/td-agent/config.d/syslog-{{ td_agent_pin_version }}.conf
    dest: /etc/td-agent/config.d/syslog-{{ td_agent_pin_version }}.conf
    owner: td-agent
    group: td-agent
    mode: 0640
  notify:
    - td-agent restart

- name: td-agent fluentd config
  template:
    src: etc/td-agent/config.d/fluentd-{{ td_agent_pin_version }}.conf
    dest: /etc/td-agent/config.d/fluentd-{{ td_agent_pin_version }}.conf
    owner: td-agent
    group: td-agent
    mode: 0640
  notify:
    - td-agent restart

- name: td-agent wp-cli-commands config
  template:
    src: etc/td-agent/config.d/wp-cli-commands-{{ td_agent_pin_version }}.conf
    dest: /etc/td-agent/config.d/wp-cli-commands-{{ td_agent_pin_version }}.conf
    owner: td-agent
    group: td-agent
    mode: 0640
  when: my.server.type is defined and my.server.type in ['pod', 'utility', 'apache']
  notify:
    - td-agent restart

- name: forward rsyslog to td-agent
  template:
    src: etc/rsyslog.d/40-fluentd.conf
    dest: /etc/rsyslog.d/40-fluentd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - rsyslog restart

# Note: deleting the obsolete file(s), these will be no-op after one CM deployment, can be removed after that.
- name: removing td-agent old syslog config
  file:
    path: etc/td-agent/config.d/syslog.conf
    state: absent
  notify:
    - td-agent restart

- name: removing td-agent old fluentd config
  file:
    path: etc/td-agent/config.d/fluentd.conf
    state: absent
  notify:
    - td-agent restart
