---
# Template used when initializing vault's secrets

sssd:
  - bind_dn
  - bind_pass

recurly:
  - api_key
  - private_key
  - subdomain

api_glues:
  - latest
  - previous

admin_keys:
  - latest

dms:
  - token

consul:
  - acl_token
  - encryption_key

dropbox:
  - storage_key
  - storage_secret

partner_keys:
  - wpvalet
  - techops

## Our client key to talk to rails my.wpe
my_wpengine_com:
  - latest

netdna:
  - alias
  - key
  - secret

mysql_root:
  - user
  - pass
  - awsuser

#mysql_replication:
#  user:
#  pass:
#  oldusers:
#
#debian:
#  pass:
#
#cloudflare:
#  user:
#  authkey:
#  zone:
#  zoneid:
#  email:
#  key:
#
#cloudflare2:
#  user:
#  authkey:
#  zone:
#  zoneid:
#  email:
#  key:
#
#dnsprovider:
#  primary:

hipchat:
  - key

hubspot:
  base_url_api:
  base_url_forms:
  apikey:
# SEV-706 double quote values with ampersands to avoid INI parsing issues in wpe.cnf ^

amazon:
  access_key:
  secret_key:

www_wpe:
  shadow:

postfix:
  relay_address:
  relay_username:
  relay_password:
  relay_port:
  corporate_relay_username:
  corporate_relay_password:

tract:
  user:
  password:
  user_bak:
  password_bak:
  url:
  ns:

statsd:
  pass:

# The following credentials *only* have access to the snappyshot.wpengin.test bucket in S3.
# That bucket is configured to remove all objects after two days.
snappyshot:
  access_key:
  secret_key:
  bucket:
  # region is currently hard-coded.
  # region:

fluentd:
  shared_key:
  user:
  pass:
  gcp_key:
#    {
#      "type":
#      "project_id":
#      "private_key_id":
#      "private_key":
#      "client_email":
#      "client_id":
#      "auth_uri":
#      "token_uri":
#      "auth_provider_x509_cert_url":
#      "client_x509_cert_url":
#    }


mailgun:
  relay_address:
  relay_port:
  postfix_relay_username:
  postfix_relay_password:

geotrust:
  partner_code:
  username:
  password:
  endpoint:
  environment:

memcache:
  host:
  port:

google:
  key:
  secret:

zendesk:
  subdomain:
  username:
  token:
  user:
  pass:

nova_aws:
  key:
  secret:
  region:

webpagetest:
  api_key:

cloudlfare:
  email:
  key:

notification_keys:
  dns_failover_key:
  dns_node_monitor_key:

aws_dynamodb_sitemonitor:
  access_key_id:
  access_secret_key:

s3_repo:
  - ro_access_key
  - ro_secret_key

github:
  wpenginebot:

pypi:
  farm_read_user:
  farm_read_password:

newrelic:
  license:
  key:

# TOPS-4504, fallback key for WPE support to get customers into NR temporarily
newrelic_support_license_key:

largefs:
  key:
  secret:

zabbix:
  mysql_user:
  mysql_pass:
  registration_secret:

gitpush:
  gitpush1_root_public_key:
  gitpush1_git_public_key:
  farm_user_public_key:
  farm_user_private_key:
