---

- name: nginx provisioning restart
  service:
    name: nginx
    state: restarted

- name: nginx reload
  service:
    name: nginx
    state: reloaded
  listen: "reload web services"

- name: nginx start
  service:
    name: nginx
    state: started
