---

- name: nginx provisioning restart
  service:
    name: nginx
    state: restarted
#  when: packer_builder_type is defined and packer_builder_type != "docker"

- name: nginx reload
  service:
    name: nginx
    state: reloaded
#  when: packer_builder_type is defined and packer_builder_type != "docker"

- name: nginx start
  service:
    name: nginx
    state: started
#  when: packer_builder_type is defined and packer_builder_type != "docker"
