---

- name: Uninstall some packages Debian family
  apt:
    pkg: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - apport
    - libpam-cracklib
    - libpam-systemd
    - lxc-common
    - lxcfs
    - lxd
    - lxd-client
    - ntpdate
    - popularity-contest
    - python-openssl
    - snapd
    - ssh-askpass-gnome
    - sshguard
    - eject

- name: ensure ansible is latest version Debian family
  apt:
    pkg: ansible
    state: latest
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  when: ansible_os_family == "Debian"
  tags:
    - skip_ansible_lint

- name: ensure common packages installed Debian family
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  with_items:
    - ack-grep
    - arping
    - clamav
    - conntrack
    - iotop
    - htop
    - iftop
    - jq
    - logrotate
    - lsof
    - ngrep
    - ntp
    - openssl
    - python-software-properties
    - rsync
    - screen
    - sysstat
    - tmux
    - unzip
    - update-notifier-common
    - zip
