---

- include: apt-get-update.yml
  tags:
    - apt-packages

- include: apt-packages.yml
  tags:
    - apt-packages

- include: apt-config.yml
  tags:
    - apt-packages

- include: pip.yml
  tags:
    - pip-packages
