---
- include: ../../testinfra.yml

- include: apt-get-update.yml

- name: Set up our apt.conf.d
  copy:
    src: "etc/apt/apt.conf.d/{{ item }}"
    dest: /etc/apt/apt.conf.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades

- name: Suppress output from update-notifier-common where it exits
  lineinfile:
    dest: /etc/cron.weekly/update-notifier-common
    state: present
    create: no
    backrefs: yes
    regexp: '^/usr/lib/ubuntu-release-upgrader/release-upgrade-motd$'
    line: '/usr/lib/ubuntu-release-upgrader/release-upgrade-motd >/dev/null 2>&1'
  failed_when: false

- name: Uninstall some packages Debian family
  apt:
    pkg: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - apport
    - libpam-cracklib
    - libpam-systemd
    - lxc-common
    - lxcfs
    - lxd
    - lxd-client
    - ntpdate
    - popularity-contest
    - python-openssl
    - snapd
    - ssh-askpass-gnome
    - sshguard
    - eject

- name: ensure ansible is latest version Debian family
  apt:
    pkg: ansible
    state: latest
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  when: ansible_os_family == "Debian"
  tags:
    - skip_ansible_lint

- name: ensure common packages installed Debian family
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  with_items:
#    - acct
    - ack-grep
#    - apache2-utils
    - arping
#    - autoconf
#    - automake
#    - autotools-dev
#    - bc
#    - binutils
#    - bison
#    - bsd-mailx
#    - build-essential
    - clamav
    - conntrack
#    - cpp
#    - cracklib-runtime
#    - curl
#    - flex
#    - g++
#    - gcc
#    - gdisk
#    - git-core
#    - git-doc
#    - gdb
#    - dstat
    - iotop
#    - gnu-standards
    - htop
    - iftop
    - jq
#    - libarchive-zip-perl
#    - libc6-dev
#    - libpam-pwquality
#    - libpcre3
#    - libpcre3-dev
#    - libpopt-dev
#    - libpwquality-tools
#    - libreadline6
#    - libreadline6-dev
#    - libsasl2-modules
#    - libssh2-1
#    - libtool
#    - libxml2-dev
#    - libxslt1-dev
#    - libyaml-dev
    - logrotate
    - lsof
#    - lynx
#    - m4
#    - make
#    - moreutils
#    - mutt
#    - mydumper
#    - nfswatch
    - ngrep
#    - nload
    - ntp
    - openssl
#    - perl
#    - perl-modules
#    - psmisc
#    - python-jinja2
#    - python-mysqldb
#    - python-paramiko
#    - python-pip
    - python-software-properties
#    - python-yaml
#    - python3-pip
#    - python3-setuptools
#    - python3-dev # for scandir?
#    - rdate
    - rsync
#    - s3cmd
    - screen
#    - ssed
#    - strace
#    - subversion
    - sysstat
#    - tcpdump
    - tmux
    - unzip
    - update-notifier-common
#    - vim-nox
#    - whois
    - zip
#    - zlib1g
#    - zlib1g-dev



- name: Install PyPI2 modules
  pip:
    name: "{{ item.module | default(item) }}"
    executable: pip2
    state: "{{ item.state | default('present') }}"
  when: "{{ item.when | default(true) }}"
  with_items:
    - boto3
    - testinfra>=1.6.0
  tags:
    - pip
    - pip2

