---

- include: root.yml
  tags:
    - root_profile

- include: clean_users.yml

- name: Gather ec2 metadata information about current instance
  action: ec2_facts  # TODO: change to ec2_metadata_facts once we're on ansible >2.4 everywhere
  register: ec2_metadata
  failed_when: false
  changed_when: false

- name: Set Hostname
  hostname:
    name: "{{ hostname_prefix }}-{{ ec2_metadata.ansible_facts.ansible_ec2_instance_id }}"
  when: hostname_prefix is defined and ec2_metadata is defined and 'ansible_facts' in ec2_metadata
