---

- name: Update CA certificates
  command: update-ca-certificates

- name: consul agent restart
  command: echo 'this should be done in user-data land?'
#  supervisorctl:
#    name: consul-agent
#    state: restarted
#  when: not consul_run_as_server

- name: consul server restart
  command: echo 'this should be done in user-data land?'
#  supervisorctl:
#    name: consul-server
#    state: restarted
#  when: consul_run_as_server
