---

- name: Configure td-agent repos
  apt_repository:
    repo: "{{ td_agent_apt_repo }}"
    state: present
    update_cache: yes

- name: Ensure pinned version of td-agent is present
  apt:
    name: td-agent
    force: yes
    state: present

- name: Ensure /etc/td-agent directory
  file:
    path: /etc/td-agent
    state: directory
    owner: td-agent
    group: td-agent
    mode: 0750

- name: Template Gemfile & Gemfile.lock for the appropriate td-agent version to /etc/td-agent
  template:
    src: "etc/td-agent/{{ item }}"
    dest: "/etc/td-agent/{{ item }}"
    owner: td-agent
    group: td-agent
    mode: 0640
  with_items:
    - "Gemfile"
    # - "Gemfile.lock"
  notify:
    - td-agent restart

- name: Template /etc/default/td-agent in order to add extra flags to the td-agent service command
  template:
    src: etc/default/td-agent
    dest: /etc/default/td-agent
    owner: td-agent
    group: td-agent
    mode: 0640
  register: td_agent_gemfile
  notify:
    - td-agent restart

- name: Ensure directory under /opt/td-agent to store bundler-managed gems
  file:
    path: "{{ td_agent_gem_path }}"
    # state: directory
    owner: td-agent
    group: td-agent
    recurse: yes

- name: Ensure bundler-managed gems for td-agent are installed
  bundler:
    executable: /opt/td-agent/embedded/bin/bundle
    gem_path: "{{ td_agent_gem_path }}"
    gemfile: "{{ td_agent_gemfile_path }}"
    state: present
  become: true  # the gems installed by this instance of bundler need to be readable by the td-agent service's user
  become_user: td-agent

- name: td-agent ca certificate
  copy:
    src: etc/td-agent/ca.pem
    dest: /etc/td-agent/ca.pem
    owner: td-agent
    group: td-agent
    mode: 0644
  notify:
    - td-agent restart

# - name: td-agent gcp key
#  template:
#    src: etc/td-agent/key.json
#    dest: /etc/td-agent/key.json
#    owner: td-agent
#    group: td-agent
#    mode: 0640
#  notify:
#    - td-agent restart

- name: td-agent config
  template:
    src: etc/td-agent/td-agent.conf
    dest: /etc/td-agent/td-agent.conf
    owner: td-agent
    group: td-agent
    mode: 0640
  notify:
    - td-agent restart

- name: ensure td-agent config folder
  file:
    path: /etc/td-agent/config.d
    state: directory
    owner: td-agent
    group: td-agent
    mode: 0750
  notify:
    - td-agent restart

# - name: td-agent syslog config
#  template:
#    src: etc/td-agent/config.d/syslog.conf
#    dest: /etc/td-agent/config.d/syslog.conf
#    owner: td-agent
#    group: td-agent
#    mode: 0640
#  notify:
#    - td-agent restart
#
# - name: td-agent fluentd config
#  template:
#    src: etc/td-agent/config.d/fluentd.conf
#    dest: /etc/td-agent/config.d/fluentd.conf
#    owner: td-agent
#    group: td-agent
#    mode: 0640
#  notify:
#    - td-agent restart
#
# - name: forward rsyslog to td-agent
#  template:
#    src: etc/rsyslog.d/40-fluentd.conf
#    dest: /etc/rsyslog.d/40-fluentd.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify:
#    - rsyslog restart
