---

- name: Ensure ufw and requisite packages are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  with_items:
    - module-init-tools
    - ufw
