version: '3'

services:
  mysql:
    image: hashicorp/packer:1.1.0

  wordpress_bootstrap:
    build: tests/helpers/bootstrap_wordpress
    image: bootstrap_wordpress
    links:
      - mysql
    depends_on:
      - mysql
    command: ["/wait-for-mysql.sh", "mysql:3306", "-t", "60", "--", "/bootstrap_wordpress.sh", "--num-installs=2"]
    env_file: .env
    volumes:
      - .compose-data/live:/live/
      - .compose-data/staging:/staging/

  gophpr:
    build: .
    image: ${IMAGE_REGISTRY}/gophpr:${COMPOSER_IMAGE_TAG}
    ports:
      - '127.0.0.1:8080:80'
      - '127.0.0.1:9501:9501'
    cap_add:
      - SYS_ADMIN
    links:
      - mysql
    depends_on:
      - mysql
      - wordpress_bootstrap
    healthcheck:
      test: ["CMD", "test", "-e", "/live/installs/.wordpress_is_ready"]
      interval: 5s
      timeout: 5s
      retries: 3
    env_file: .env
    volumes:
      - .compose-data/live:/live/
      - .compose-data/staging:/staging/
      - .compose-data/newrelic/:/run/newrelic/

  newrelic:
    image: wpengine/newrelic-daemon
    environment:
      - NR_PORT=/run/newrelic/newrelic.sock
    volumes:
      - .compose-data/newrelic/:/run/newrelic/
