---

dependencies:
  - role: supervisor
    supervisor_programs:
      - name: 'consul-agent'
        command: /usr/local/bin/consul agent -config-file=/etc/consul.d/agent.hcl
        state: present
        user: consul
        configuration: |
         autostart=false
         autorestart=true
         startretries=1
         startsecs=1
         redirect_stderr=true
         stderr_logfile=/var/log/consul-agent.error.log
         stdout_logfile=/var/log/consul-agent.log
         killasgroup=true
         stopasgroup=true
      - name: 'consul-server'
        command: /usr/local/bin/consul agent -server -bootstrap-expect {{ consul_cluster_size }} -config-file=/etc/consul.d/server.hcl
        state: present
        user: consul
        configuration: |
         autostart=false
         autorestart=true
         startretries=1
         startsecs=1
         redirect_stderr=true
         stderr_logfile=/var/log/consul-server.error.log
         stdout_logfile=/var/log/consul-server.log
         killasgroup=true
         stopasgroup=true
