---
# PHP specific variables (override of common/defaults)
# This file describes the use of PHP5.5 and PHP5.6 on Ubuntu Trusty to provision
# and install web stack as 5.6 and cli as 5.5

php_apache_version: 5.6
php_apache_module: php5.6
php_apache_conf_path: /etc/php/5.6/apache2
php_apache_conf_module_path: "{{ php_apache_conf_path }}/conf.d"
php_apache_avail_path: /etc/php/5.6/mods-available
php_apache_pecl_modules: []

php_cgi_version: 5.6
php_cgi_conf_path: /etc/php/5.6/cgi
php_cgi_avail_path: /etc/php/5.6/mods-available

php_cli_version: 5.5
php_cli_conf_path: /etc/php5/cli
php_cli_avail_path: /etc/php5/mods-available

php_wpcli_version: 5.6
php_wpcli_conf_path: /etc/php/5.6/cli
php_wpcli_avail_path: /etc/php5/mods-available
php_wpcli_binary: /usr/bin/php5.6

php_usr_lib: /usr/lib/php/20131226
