---

- name: Ensure vault group
  group:
    name: "{{ vault_group }}"
    system: yes

- name: Ensure vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    home: "{{ vault_data_path }}"
    shell: /usr/sbin/nologin
    state: present

- name: Import install vault tasks
  import_tasks: install.yml

- name: Import nginx tasks
  import_tasks: nginx.yml

- name: Ensure vault config directory
  file:
    path: /etc/vault.d
    state: directory
    owner: vault

- name: Ensure vault ssl directory
  file:
    path: /etc/vault.d/ssl
    state: directory
    owner: vault

- name: Template vault SSL
  copy:
    content: "{{ item.contents }}"
    dest: "{{ item.name }}"
    owner: vault
    group: root
    mode: 0400
  with_items:
    - { contents: "{{ vault_ssl_cert }}", name: "{{ vault_ssl_crt_path }}"}
    - { contents: "{{ vault_ssl_ca_cert }}", name: "{{ vault_ssl_ca_crt_path }}"}
    - { contents: "{{ vault_ssl_key }}", name: "{{ vault_ssl_key_path }}"}
  no_log: true
  notify:
    - 'Vault Restart'

- name: Ensure vault CA cert directory
  file:
    path: /usr/share/ca-certificates/wpengine/
    state: directory

- name: Template vault SSL CA
  copy:
    content: "{{ vault_ssl_ca_cert }}"
    dest: /usr/share/ca-certificates/wpengine/vault_ca.crt
    owner: root
    group: root
    mode: 0400
  notify: Update CA certificates

- name: Ensure vault SSL is loaded in /etc/ca-certificates.conf
  lineinfile:
    dest: /etc/ca-certificates.conf
    line: wpengine/vault_ca.crt

- name: Template vault config file at /etc/vault.d/vault.hcl
  template:
    src: etc/vault.d/vault.hcl
    dest: /etc/vault.d/vault.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - 'Vault Restart'
