---

- include: ../../testinfra.yml


- name: Ensure vault group
  group:
    name: "{{ vault_group }}"
    system: yes

- name: Ensure vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    createhome: no
    shell: /usr/sbin/nologin
    state: present


- include: install.yml

- name: Gather about currently running instance
  ec2_facts:
  when: packer_builder_type is not defined or packer_builder_type == 'amazon-ebs'

- include: nginx.yml

- name: Ensure vault config directory
  file:
    path: /etc/vault.d
    state: directory

- name: Ensure vault ssl directory
  file:
    path: /etc/vault.d/ssl
    state: directory

- name: Template vault SSL
  copy:
    src: /tmp/{{ item }}
    dest: /etc/vault.d/ssl/{{ item }}
    owner: root
    group: root
    mode: 0400
  with_items:
    - vault.crt.pem
    - vault.key.pem
  notify:
    - 'vault restart'

- name: Ensure vault CA cert directory
  file:
    path: /usr/share/ca-certificates/wpengine/
    state: directory

- name: Template vault SSL CA
  copy:
    src: /tmp/ca.crt.pem
    dest: /usr/share/ca-certificates/wpengine/vault_ca.crt
    owner: root
    group: root
    mode: 0400
  register: template_ca_cert

- name: Ensure vault SSL is loaded in /etc/ca-certificates.conf
  lineinfile:
    dest: /etc/ca-certificates.conf
    line: wpengine/vault_ca.crt

- name: Update CA certificates
  command: update-ca-certificates
  when: template_ca_cert.changed

- name: Template vault config file at /etc/vault.d/vault.hcl
  template:
    src: etc/vault.d/vault.hcl
    dest: /etc/vault.d/vault.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - 'systemctl daemon-reload'
    - 'vault restart'

- name: Template vault service config file
  template:
    src: etc/systemd/system/vault.service
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: 0644
  notify:
    - 'systemctl daemon-reload'
    - 'vault restart'

- name: Copy various vault helper scripts to /usr/local/bin
  copy:
    src: "usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - initialize_vault_secrets

- name: Ensure /etc/wpengine/vault/secret_templates directory
  file:
    path: /etc/wpengine/vault/secret_templates
    state: directory

- name: Copy credential templates to /etc/wpengine/vault/
  copy:
    src: "etc/wpengine/vault/secret_templates/"
    dest: "/etc/wpengine/vault/secret_templates"
    owner: root
    group: root
    mode: 0644
