---

- name: /etc/logrotate.d/syslog
  template: src=etc/logrotate.d/rsyslog dest=/etc/logrotate.d/rsyslog owner=root group=root mode=0644

- name: Delete harmful dpkg-dist files
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /etc/logrotate.d/*.dpkg-dist
