---

- name: Install stock nginx
  apt:
    pkg: nginx
    state: present
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time | default(600) }}"
  tags:
    - packages
  notify:
    - nginx start
    - nginx provisioning restart

- name: Do /etc/nginx/nginx.conf
  template:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: nginx reload
  tags:
    - nginx_conf

- name: Remove default symlink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: nginx reload

- name: Do /etc/nginx/sites-enabled/all
  template:
    src: etc/nginx/sites-enabled/all
    dest: /etc/nginx/sites-enabled
    owner: root
    group: root
    mode: 0644
  notify: nginx reload

- name: Enable nginx service
  service:
    name: nginx
    enabled: yes

- name: Do nginx logrotate
  template:
    src: etc/logrotate.d/nginx
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: 0644

- name: Ensure /etc/wpengine/nginx/ subdirectories
  file:
    dest: /etc/wpengine/nginx/{{ item }}
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - certs

- name: Generate custom dhparams
  command: openssl dhparam -out /etc/wpengine/nginx/certs/dhparam.pem {{ nginx_dhparam_bits }}
  args:
    creates: /etc/wpengine/nginx/certs/dhparam.pem

- name: Ensure dhparam permissions
  file:
    path: /etc/wpengine/nginx/certs/dhparam.pem
    state: file
    owner: root
    group: www-data
    mode: 0640
