#! /bin/sh -e
### BEGIN INIT INFO
# Provides:             proxsmtp
# Required-Start:       $syslog $network
# Required-Stop:        $syslog $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Start the proxsmtp proxies
# Description:          Start all the proxsmtp proxies from /etc/proxsmtp/*.conf
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=proxsmtp
DAEMON=/usr/sbin/proxsmtpd
RUNDIR="/var/run/${NAME}"

 . /lib/lsb/init-functions

lsconfs() {
    ls "/etc/${NAME}"/*.conf 2>/dev/null
}

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

mkdir -p "${RUNDIR}"

# Gracefully exit if there is no available config files
lsconfs > /dev/null || exit 0

d_start() {
    start_daemon -p "${1}" ${DAEMON} -p "${1}" -f "${2}"
}

d_stop() {
    killproc -p "${1}" "`basename "${DAEMON}"`"
}

d_all() {
    cmd="${2}"

    log_daemon_msg "${1} smtp proxies"
    lsconfs | while read -r conf; do
        inst=`basename "${conf}" .conf`
        pidfile="${RUNDIR}/${inst}.pid"
        runas=`grep -shoP '(?<=^User: )\w+' "${conf}" || echo root`
        touch "${pidfile}"
        chown "${runas}" "${pidfile}"
        log_progress_msg "${inst}"
        "${cmd}" "${pidfile}" "${conf}"
    done
    log_end_msg 0
}

case "$1" in
    start)
        d_all "Starting" d_start
	;;
    stop)
        d_all "Stopping" d_stop
        ;;
    force-reload|restart)
        d_all "Stopping" d_stop
	sleep 0.5
        d_all "Starting" d_start
	;;
    status)
	RUNNING=`pgrep -f ${DAEMON}|wc -l`
	if [ "${RUNNING}" -gt 0 ]; then
	   log_success_msg "proxsmtp is running with ${RUNNING} thread(s)"
	   exit 0
	else
	   log_success_msg "proxsmtp is not running"
	   exit 3
	fi
    ;;
    *)
	echo "Usage: ${0} {start|stop|restart|status|force-reload}" >&2
	exit 1
	;;
esac

exit 0
