---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: wpengine/ansible:latest
#    command: {{ supervisor_bin_path }} -c /etc/supervisor/supervisord.conf
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: E501
