---

# This playbook should provision/update our vault servers

- name: Vault
  hosts: all
  connection: local
  user: root

  vars:
    - cache_valid_time: 600
    - nginx_wildcard_certificates: []

  pre_tasks:
#    - include: shared-load-vars.yml
#      check_mode: no
#      tags: always

      # for tasks ineligible for tags:always
#    - include: shared-pre-tasks.yml

  # CAUTION: Applying a when to a role also applies it to all the role's dependencies and handlers. A skipped role may
  # prevent the handlers or additional dependencies on that role from being executed later
  roles:
#    - { role: common, tags: common }
#    - { role: nginx }
#    - { role: ldap-client, when: not is_vagrant }
    - { role: vault, tags: role_vault }
#    - { role: security, tags: security }
#    - { role: zabbix-agent, tags: zabbix, when: register_with_zabbix }

#  post_tasks:
#    - include: shared-post-tasks.yml
