---

- name: Install chkrootkit
  apt:
    state: installed
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  with_items:
    - chkrootkit

- name: ensure /var/log/chkrootkit
  file:
    path: "/var/log/chkrootkit"
    state: "directory"
    owner: "root"
    group: "root"
    mode: 0755

- name: ensure chkrootkit cron
  copy:
    src: "etc/cron.daily/chkrootkit"
    dest: "/etc/cron.daily/chkrootkit"
    owner: "root"
    group: "root"
    mode: 0755

- name: ensure chkrootkit config
  template:
    src: "etc/chkrootkit.conf"
    dest: "/etc/chkrootkit.conf"
    owner: "root"
    group: "root"
    mode: 0644

- name: ensure chkrootkit rsyslog rule
  copy:
    src: "etc/rsyslog.d/chkrootkit.conf"
    dest: "/etc/rsyslog.d/chkrootkit.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart rsyslog

- name: ensure chkrootkit logrotate rule
  copy:
    src: "etc/logrotate.d/chkrootkit"
    dest: "/etc/logrotate.d/chkrootkit"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart rsyslog
