---

- name: add Zabbix user to RDS database
  mysql_user:
    name: "{{ creds.zabbix.mysql_user }}"
    password: "{{ creds.zabbix.mysql_pass }}"
    host: "%"
    login_host: "{{ cluster.mysql_host }}"
    login_user: "{{ creds.mysql_root.awsuser }}"
    priv: "*.*:USAGE"
    login_password: "{{ creds.mysql_root.pass }}"

- name: Copy zabbix userparameter file for RDS connectivity
  copy:
    src: "etc/zabbix/zabbix_agentd.d/userparameter_rds_connectivity.conf"
    dest: "/etc/zabbix/zabbix_agentd.d/userparameter_rds_connectivity.conf"
    owner: zabbix
    group: zabbix
    mode: 0644
  notify: zabbix agent restart

