---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ../../molecule/.yamllint
platforms:
  - name: role_zabbix_agent_molecule_ubuntu_1604
    image: jeffreymhogan/ansible:16.04
provisioner:
  name: ansible
  env:
    ../../../../../artifacts/ansible
  config_options:
    defaults:
      callback_whitelist: junit
      stdout_callback: only_errors
  playbooks:
    create: ../../../../molecule/create.yml
    destroy: ../../../../molecule/destroy.yml
    prepare: ../../../../molecule/prepare.yml
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junit-xml: ../../../../../artifacts/molecule/zabbix_agent_role.xml
    junit-prefix: testinfra_zabbix_agent
  lint:
    name: flake8
    options:
      ignore: E501
